version: '3'

services:
  web:
    container_name: modoboa_api
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: ".."
      DB: "SQLITE"
      DEBUG: "True"
    command: sh -c "cd test_project && python3 manage.py migrate && python3 manage.py load_initial_data && python3 manage.py runserver 0:8000"
    volumes:
      - .:/code

  new_admin:
    container_name: modoboa_new_admin
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.admin.dev
    ports:
      - 8080:8080
    command: "" 
    volumes:
      - ./frontend/:/home/node/
    command: "yarn serve"
    depends_on:
      - web
